### ISSUE TITLE
Temperature transition

### ISSUE THREAD

**Issue by Pentasis** [BlackJar72/ClimaticBiomePlacement#13]
Not sure if this is a bug or not, but I notice sharp transitions between biome temperatures. Attached you see an Extreme hill (Alpine) next to a Savanna.

Also, I found that putting birch and autumnal forests in the ForestCool config makes more sense. Just a suggestion/opinion.
![2019-01-11_12 49 14](https://user-images.githubusercontent.com/7046024/51032352-fec7c880-159f-11e9-801f-09570301ce78.png)

**Comment by BlackJar72** [comment]
Alpine biomes are a special case -- they are allowed to appear in subtropical areas (where plains and savannas can mixe) on the basis mountains can appear anywhere irl, even at the equator, and have snowy peeks anywhere if high enough.  I only don't allow them in the topics because the height of jungle trees next to vanilla extreme hills makes them look very wrong.  I have thought of adding temperature-specific mountains, in a way similar to oceans and islands, but haven't because there aren't that many alpine vanilla biomes.  I suppose I could add more biomes -- I just don't want to use up too many IDs since people may also use BoP, Traverse, dimension mods, etc.

Birch and autumnal forests  (from Traverse) get their position because the "cool" biomes only exist with BoP, or if you intentionally turn on the BoP-typical settings.  I use a mix or look, name, and actual in-code temperatures when deciding what goes where.

This is intentional at this point, though I could consider a redesign.  Maybe I could add an extreme mountains fake biome and have it represent peeks surrounded by something more specific to the region as foothills (extreme hills for non-icy temperate and cooler)?  What do you think of these ideas?

**Comment by Pentasis** [comment]
Understood. I think if you could add a buffer-biome (foothills) between extreme-hills and warm/hot biomes as a transition it would work.

I indeed use BoPClimateTable and use traverse badlands as a cool plains biome since it looks it could belong in either warm or cold climates. A look like that could perhaps also work for foothills?

**Comment by BlackJar72** [comment]
I think what I'll do is have more alpine types: cold, wet, dry, warm-wet, warm-dry, hot-wet, and hot-dry (and maybe desert?).  Then add for new biomes, maybe with fake variants, for subtropical and tropical mountains; the trees on these are based on forests one level cooler (because of elevation).

**Comment by BlackJar72** [comment]
Try the newest version -- it adds warmer extreme hills variants for warmer climates.

As for the birch forests, well, I'm keeping things referenced to vanilla by default, but if you want to move them that's what all those files are for.

Just be sure you are this to your biome variants:
`
minecraft:ice_mountains:1 1.5, 0.5

minecraft:extreme_hills:1 1.5, 0.5

minecraft:extreme_hills_with_trees:1 1.5, 0.5

climaticbiomesjbg:warm_mountain:1 1.5, 0.5

climaticbiomesjbg:warm_mountain_trees:1 1.5, 0.5

climaticbiomesjbg:hot_mountain:1 1.5, 0.5

climaticbiomesjbg:hot_mountain_trees:1 1.5, 0.5
`

**Comment by BlackJar72** [comment]
``
