### ISSUE TITLE
Potential errors in default configs

### ISSUE THREAD

**Issue by QuantumStatement** [BlackJar72/ClimaticBiomePlacement#15]
When I look at default configs I fing some errors
1. Missing commas in `savanna.cfg`
https://github.com/BlackJar72/ClimaticBiomePlacement/blob/83ea8bdb86450f51cfe67d253fd9b6b947b66f22/main/resources/assets/climaticbiomesjbg/BiomeLists/Minecraft/Savanna.cfg#L2-L3
2. Same biome in noise distribution
https://github.com/BlackJar72/ClimaticBiomePlacement/blob/83ea8bdb86450f51cfe67d253fd9b6b947b66f22/main/resources/assets/climaticbiomesjbg/BiomeLists/Minecraft/Desert.cfg#L16
I think it should be like this
`noise(minecraft:mesa, 5, minecraft:mutated_mesa)`

**Comment by BlackJar72** [comment]
Well with the mesas it was supposed to be the plateau and non-plateau mutated biomes:

`noise(minecraft:minecraft:mutated_mesa_clear_rock, 5, minecraft:mutated_mesa)`

The commas are supposed to be in the Savanna config for consistency and to make it more clear to human readers (it does the same thing though, since comma and white space are both set as delimiters).

I have fixed these in the files.

**Comment by BlackJar72** [comment]
Thanks, I've fixed it for the next version.

**Comment by QuantumStatement** [comment]
Some questions about `taiga.cfg`
https://github.com/BlackJar72/ClimaticBiomePlacement/blob/9a4d432ec31670986502988eab383546f0d005a6/main/resources/assets/climaticbiomesjbg/BiomeLists/Minecraft/Taiga.cfg#L9
Maybe it should be `minecraft:redwood_taiga_hills`?
