### ISSUE TITLE
Version 2.6.2 freezes trying to load biomes

### ISSUE THREAD

**Issue by Zergmazter** [BlackJar72/ClimaticBiomePlacement#18]
Took me a while to find the root of the problem in my 100+ modpack. I started to notice that my world generation began to freeze just like back in 1.7.10 (very annoying). Also sometimes while creating a world it would never load and stay frozen creating terrain.

I changed the world generation to BOP, then Vanilla and the issue was resolved. I then chose climatic biomes world gen and the issue returned. Sometimes stuck at "creating terrain" and most other stuck loading a biome. 

While its stuck loading a biome, entities stop moving, chests are not accessible etc...
Here is a screenshot:

![2019-01-25_05 19 29](https://user-images.githubusercontent.com/17000034/51740320-b27d8d80-2061-11e9-9650-ad40aeb92cc1.png)

I'm not sure exactly which version started causing this as it took me a while to figure out it was your mod, and I just kept updating when you released an update. I can tell you that this issue did not happen before. It was one of your later updates.

If you need me to further test this let me know. I can test and find the last version this was not happening on and let you know.

**Comment by BlackJar72** [comment]
Are you using anything that would cause a treasure map (like those to woodland mansions / ocean monuments) to generate?  If so that could be the problem. since it doesn't work well with those and I don't think that can be fixed -- the two systems are just too different.  Otherwise, a very short lag spike (about 1/4 second) is typical when a new climate region is first generated; this should happen about every 4k blocks.  Simply opening up the trade for woodland maps can hang the game while it generates a 100 or more climate maps to find a mansion, and similar modded systems may do the same.

This may actually be what kills the whole project in the long term -- it's just too different to work with some things designed for vanilla world-gen.

**Comment by Zergmazter** [comment]
Hmmm well I do have these that generate structures:
-Ancient Warfare 2
-Coral Reef
-Streams
-Recurrent Complex
-Ruins
-Rogue Like Dungeons
-Shipwrecks
-Treasure2

I know I might have over done it with the generation mods. Never thought it would cause issues. I'm gonna test and single out which generation mods is clashing with yours. By the way it freezes for like 5 minutes lol.

I will do that after I sleep some. Its 6am here and I have not slept. I'll update you soon.

**Comment by Zergmazter** [comment]
To tell you the truth I can lose a few of those. I like what your mod does so much better.

**Comment by BlackJar72** [comment]
Well, I can't tell without testing, but I might be suspicious of Treasure2 and maybe streams(?).

I'll say that Roguelike Dungeons and the Ruins are safe.  I have those on my worlds, no problem.

The real problem isn't with structures, it's with finding locations for distant things (which usually happen to be structures) -- for example: in vanilla, the mansions are not a problem but cartographer's maps to locate them are.  I'm worried about 1.13 and all those treasure maps in ships.

**Comment by Zergmazter** [comment]
Well I removed treasures 2, and it improved tremendously. There are still lag spikes lasting from 2 seconds to 30 seconds, but they are only an occasional occurrence. the 30 second spikes when loading a biome are more uncommon now. My game improved about 75% I'd say. 

Still need to figure out what other mod is causing the remaining 30 sec spikes.
