### ISSUE TITLE
Fail to create world if Write to BiomeList is true

### ISSUE THREAD

**Issue by edenhack** [BlackJar72/ClimaticBiomePlacement#22]
Not 100% sure why this happens as I'm no coder, just really good at reversing what the crash report said. Something about the try statement you have in climaticbiome/compat/userdef/defreader.class where it attempts a write to a biomelist will cause a server crash on startup. /shrug idk why, but turning off the write to biome list will allow the server to startup as usual.

**Comment by edenhack** [comment]
I'd like to note my modlist is huge, so it's probably a compact issue on my end, but its always nice to tell a coder whats up when you bug out their code. I hope this doesn't stress you out too much, im sure this is an outlier issue.

**Comment by BlackJar72** [comment]
Are you using Just Enough ID and a large number of mods with biomes?  I'm not sure if that would do anything, actually.  Also, could you actually post the crash report and maybe the mod list?

It would be really great to at least know what error was and at what line.

**Comment by edenhack** [comment]
Oh goodness me i forgot to add that information I'm terribly sorry. Here is the crash report
[crash-2019-04-06_08.43.40-server.txt](https://github.com/BlackJar72/ClimaticBiomePlacement/files/3050687/crash-2019-04-06_08.43.40-server.txt)

And here is the modlist
[modlist.txt](https://github.com/BlackJar72/ClimaticBiomePlacement/files/3050688/modlist.txt)

I'd like to note, i only got the error after my most recent additions to the modpack. So I'm going to assume that either SteamAgeRevolution or Bewitchment caused the issue (more than likely bewitchment as its currently indev).

Prior to those editions I had no issues with the WriteTo function with my server. I do have custom biomes, I do have Just Enough IDs.... ah wait, possibly an issue with Just Enough IDs integration, I did add that as well this last update to my pack.

**Comment by BlackJar72** [comment]
I was going to say, it looks like one of two things have happened, either: (a) another mod has core modded _WorldType.java_, or (b) Forge has changed something between versions (I don't know if you changed Forge versions).  Since it can't find a method of a vanilla class, someone must have changed that class.

It looks like, though, that it's not the biome lists that causes the problem, but the new feature of listing world types -- apparently either "getName()" or "canBeCreated()" has been removed or had its (obfuscated) name changed.  So for now, you can roll back to 2.7.x or just turn the lists off to stop the crash.  Also, if you updated this recently that could have been why you started seeing crashed now.

**Comment by BlackJar72** [comment]
Try this and see if it helps (do not enable WorldTypes to be created):
[http://www.mediafire.com/file/ry2ce8b99v4ru2d/ClimaticBiomes-2.8.1-MC1.12.2.jar/file](http://www.mediafire.com/file/ry2ce8b99v4ru2d/ClimaticBiomes-2.8.1-MC1.12.2.jar/file)

**EDIT:** The problem seems to have been with "_canBeGenerated()_", which seems to have been removed by either Forge or someone's core mod.  Maybe someone concluded a world type that can't be generated is pointless anyway?  Try the new version uploaded at Curse.
