### ISSUE TITLE
Crash when using 'lostcities' chunk provider

### ISSUE THREAD

**Issue by Bulldog83** [BlackJar72/ClimaticBiomePlacement#29]
Game crashes when using chank provider from The Lost Cities mod.

S:ChunkProvider=lostcities

Crash reports:
https://gist.github.com/Bulldog83/0ecdb9358dd0ea0b2c01981f18334ff2
https://gist.github.com/Bulldog83/0ac3b031822845eec3cbc8c3e267b1ef
https://gist.github.com/Bulldog83/9e00ba79b357251dca9a33338f3c1bd5

Minecraft: 1.12.2
Forge: 14.23.5.2835
CBP: 2.10.2
Lost Cities: 2.0.20

**Comment by BlackJar72** [comment]
It doesn't handle my "fake" biomes since they aren't registered as normal biomes.

I didn't realize this would be an issue.  I'm guessing most of this could be fixed by replacing all fake biomes registered versions.  Any biome configured with an extra number on the end like "...:1" will be a problem, the extra prefix would just have to be removed.

The one thing I'd need to make a change to the code would be the deep river since that is hard coded.

**Comment by BlackJar72** [comment]
Try this potential next patch and see if it helps:
[http://www.mediafire.com/file/dnt7p0luz7sz06o/ClimaticBiomes-2.10.3-MC1.12.2.jar/file](http://www.mediafire.com/file/dnt7p0luz7sz06o/ClimaticBiomes-2.10.3-MC1.12.2.jar/file)
It should treat all fake biomes as their parent biomes whenever using the lost cities chunk provider.  If if you don't have any problems I'll make it official / put it on Curse.

**Comment by Bulldog83** [comment]
Hm. Looks like it works. Thanks!

**Comment by BlackJar72** [comment]
Good, I'll upload the patch to CurseForge then.
