### ISSUE TITLE
Zoesteria Biomes Fail to Load

### ISSUE THREAD

**Issue by WenXin20** [BlackJar72/ClimaticBiomePlacement#38]
Minecraft 1.12.2
Forge v14.23.5.2838
Climatic Biomes v2.13.6
Zoesteria Biomes v1.4.10

While creating a new world, I noticed the following printed in the logs. Only Zoesteria seem to be failing to load.
```
Failed to load biome: 
 	 Tag: biome
 	 Full String: biome(valoegheses_be:stony\\ reef)
 	 File: OceanWarm.cfg
```
[Full Biome List](https://gist.github.com/WenXin20/126315382182fa22f7caec31a20b4f0b)
[Full Log](https://gist.github.com/WenXin20/5e722cfcd2b4c037ddb45e7db29987b1)

**Comment by BlackJar72** [comment]
This is mostly the Zoestria devs fault ... I almost didn't include it because there is white space in the resource locations (this is really bad).  I thought I'd found a work-around for that mistake, but maybe the workaround isn't working.

If this continues to be a problem I may actually just remove that portion and not claim to support Zoestria.  Sorry if this is a disappointment, but there is only so much I can do to fix someone else's mistake.

The same goes for Tolkien Mobs, for the same reason.

**Comment by WenXin20** [comment]
It's ok if nothing can be done, just thought I would report it. Although I think Tolkien Mobs Biomes is working, I didn't see any errors for that one.

**Comment by BlackJar72** [comment]
Well, let me ask this ... is that the **only biome** that causes trouble?

**Comment by WenXin20** [comment]
The full biome list link above shows the ones that errored. So no, it's not the only one. Looks like 27 in that list, all from Zoesteria.
