### ISSUE TITLE
Nether generates as the overworld

### ISSUE THREAD

**Issue by zlyfire** [BlackJar72/ClimaticBiomePlacement#50]
The Nether does not generate using BoP, NetherEX, or even Vanilla generation or biomes. Instead, it is generated using the same style as the overworld does with Climatic Biome Placement.
I had tried to regenerate the Nether multiple times with the following configurations:
With CBP and BoP (Failure)
With CBP, BoP, and NetherEX (Failure)
Without CBP, with the others (Success)
It only succeeded with CBP disabled, leading me to believe the nether was overlooked as being excluded in the terrain/biome generator.

**Comment by BlackJar72** [comment]
I'm guessing this is on 1.14.4, since I've never seen it in 1.12.2, with or without BoP.  Currently,I can't even get the dev environment to do test runs and I don't plan on fight with it to make it work.  Really though, after much soul searching as to what I want my time to into I've decide to "retire" from modding, so unfortunately this will never be fixed.  The 1.14.4 update was really more of a WIP test of the core system for people to look at if they wanted; since it has many flaws and people have had a change to look I will likely archive the apha and this will simply be 1.12.2 only mod.

Sorry if this is disappointing.
