### ISSUE TITLE
Crash: Exception generating new chunk

### ISSUE THREAD

**Issue by henrique-klayton** [BlackJar72/ClimaticBiomePlacement#9]
I am having a crash while exploring the world. I was using some mods but removed them and discovered that the game crashes while using Climatic Biomes.

Minecraft 1.12.2
Forge 2768
Climatic Biomes 2.3.3
Biomes O Plenty 7.0.1.2422

https://pastebin.com/aHKh2QHK

**Comment by BlackJar72** [comment]
What mods did you remove?  

EDIT:  Its not a missing biome -- those just generate as ocean and give you some ugly cliffs.  I'll have to look into it, I have no idea what is happening right now.

**Comment by BlackJar72** [comment]
It turns out that while it could use defaults for normal biomes based on the vanilla system my extended range sub biome system (so far used for deep versions of vanilla rivers) was not so forgiving.  I forgot to register the deep frozen river, so it crashed since it was trying to generate terrain with no biome at all.

The latest update fixed the crash.
